version: 1.0
Resources:
  -TargetService:
    Type: AWS::ECS::Service
    Properties:
      TaskDefinition: arn:aws:ecs:ap-south-1:610018615348:task-definition/disbursement:1
      LoadBalancerInfo:
        ContainerName: "disbursement"
        ContainerPort: "8083"
      PlatformVersion: "Latest"
